### ISSUE TITLE
[1장][민희] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by leeminhee119** [KJ-StudyWithMe/modern-react-deep-dive#10]
### 퀴즈

다음 코드에서 출력될 내용을 작성해주세요! 각각이 출력된 이유를 함께 작성해주세요

```js
const Counter = () => {
	let count = 0;
	return {
		count,
		setCount: (newVal) => {
			count = newVal;
		},
		getCount: () => count,
	}
}

const {count, setCount, getCount} = Counter();
setCount(10);
console.log(count); // (1)
console.log(getCount()); // (2)
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
(1) 0  

이유: count는 Counter() 내에서만 유효하므로 외부에서 접근이 불가하다. 따라서 Counter가 처음에 반환한 count 값인 0이 그대로 출력된다.  

(2) 10  
이유: setCount(10)이 호출되며 클로저를 생성, 클로저 내부의 count 값이 생성된 환경을 기억해 이를 10으로 업데이트시킬 수 있다. 마찬가지로 getCount()도 클로저를 생성해 count가 생성된 환경을 기억하고 해당 값을 리턴할 수 있다.

정확하지 않거나 더 좋은 설명이 있다면 공유해주세요 🤓
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) 10
(2) 10
</div>
</details>

**Comment by jkea1** [comment]
(1) 0
블록 레벨 스코프를 가지는 let 으로 선언한 count 변수는 코드 블록 내에서만 유효하며 코드 블록 외부에서는 참조할 수 없습니다. 따라서 Counter가 처음에 반환한 count 값인 0이 그대로 출력됩니다. 

(2) 10
setCount() 함수를 통해 내부 변수를 변경할 수 있습니다. 

클로저 개념 정립이 아직 완전히 안돼서 설명하려니 조금 어렵네요.

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) 0
Counter 함수 내부에는 let으로 선언된 count 변수가 존재하고, 객체를 반환하고 있습니다.
만약 Counter() 함수를 호출하는 구문을 만났을 때, 반환되는 객체의 형태는 다음과 같습니다.

{
  count: 0,
  setCount: (newVal) => { count = newVal; },
  getCount: () => count,
}

여기서 중요한 점은 setCount, getCount 함수 내부에서 사용되는 count는 Counter 함수의 선언적 환경 레코드에 저장된 let count = 0; 를 가리키고 있다는 부분입니다.

그렇기 때문에 setCount(10) 를 호출한다고 해도 Counter 함수의 선언적 환경 레코드에 저장된 count의 값이 10으로 증가할 뿐이지, 이미 Counter() 호출로 반환된 객체 내부의 count가 증가하지는 않습니다.

(2) 10
getCount 함수의 내부에서 사용되는 count 변수는 Counter 함수의 선언적 환경 레코드에 저장된 count의 값을 가리키고 있습니다.
이전에 setCount(10) 을 호출해서,  Counter 함수의 선언적 환경 레코드에 저장된 count의 값을 10으로 만들었으니 
getCount() 를 호출해서 해당 count 값을 반환하면 10이 출력됩니다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) `0`
(2) `10`

**`Counter` 함수 내부에 선언된 `count` 변수**와 **외부에 선언된 `count` 변수**는 서로 다른 변수다. `Counter` 함수 내부에 선언된 `count` 변수는 블록 스코프를 가지므로 외부에 노출되지 않는다. 대신 `setCount`와 `getCount` 함수를 통해서만 내부 `count` 변수를 조작하고 조회할 수 있도록 클로저를 통해 관리된다. 초기값이 0일 때 외부 `count` 변수에 내부 `count` 변수의 값을 선언했기 때문에 이는 내부 `count`의 값을 조작하더라도 변하지 않으므로 0이 출력되고, 내부 `count` 변수를 조작하는 함수 `setCount(10);`을 호출했기 때문에 `getCount()`로 호출하는 내부 `count` 변수의 값은 10으로 출력된다.



</div>
</details>
