### ISSUE TITLE
[1장][상훈] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by bbearcookie** [KJ-StudyWithMe/modern-react-deep-dive#11]
### 퀴즈

아래 함수의 실행 결과를 예측하고, 이유를 서술해주세요.

```js
function timer(i) {
  let start = i;

  const callback = (i) => {
    setTimeout(() => {
      Promise.resolve().then(() => {
        console.log(`--${i}--`);
      });

      setTimeout(() => {
        console.log(`-${i}-`);
      });

      console.log(`---${i}---`);
    }, (start - i) * 1000);
  };

  for (let j = 0; j <= i; j += 1) {
    callback(j);
  }
}

timer(5);
```

<details>
<summary>정답</summary>
<div markdown="1">    

### 답

```
---5---
--5--
-5-
---4---
--4--
-4-
---3---
--3--
-3-
---2---
--2--
-2-
---1---
--1--
-1-
---0---
--0--
-0-
```

### 해설

1. 먼저, 전역 실행 컨텍스트에서 `timer` 함수가 호출되면, `timer` 의 함수 실행 컨텍스트가 생성됩니다.  
2. `timer` 함수 실행 컨텍스트의 Declarative Environment Record에 `start` 가 초기화됩니다.  
3. `timer` 함수의 인자로 전달한 5가 `start` 의 값에 할당됩니다.
4. `i` 가 5이 될 때까지 1씩 증가하면서 callback 함수를 실행하면, 아래 로직이 수행됩니다.
    1. 5초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (0 출력)
    2. 4초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (1 출력)
    3. 3초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (2 출력)
    4. 2초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (3 출력)
    5. 1초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (4 출력)
    6. 0초 뒤에 실행되는 콜백이 setTimeout 에 등록됩니다. (5 출력)

여기서, setTimeout에 등록된 콜백 내부에는 Promise`(--x--)`, setTimeout`(-x-)`, 동기 함수`(---x---)` 하는 동작을 수행합니다.
우선 순위가 동기 함수 < Promise < setTimeout 이므로, 이와 같은 출력 결과를 보입니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
---5---  

--5--  
-5-  
---4---  
--4--  
-4-  
---3---  
--3--  
-3-  
---2---  
--2--  
-2-  
---1---  
--1--  
-1-  
---0---  
--0--  
-0-  




setTimeout은 비동기 함수로 콜 스택에서 처리되지 않고, 콜백함수가 태스크 큐로 옮겨진다.  
그 중에서도 동기 코드인 console.log문이 가장 먼저 실행되고, promise는 우선순위가 더 높은 마이크로 태스크 큐로 옮겨져 태스크 큐의 setTimeout보다 먼저 실행된다.  
i가 5인 놈부터 실행되는 이유는 타이머 시간이 가장 빨리 완료돼서?
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
`---${i}---`
`--${i}--`
`-${i}-`

순으로 실행된다.
이유 :  `---${i}---`은 비동기 함수로 안감싸져있어 먼저 실행되고, `--${i}--`은 Promise로 감싸져있는데 setTimeout보다 우선순위가 높은 비동기 함수이기때문에 `-${i}-`보다 먼저 실행된다.





</div>
</details>

**Comment by jkea1** [comment]
Call Stack 에 for문으로 인해 `[callback(0), callback(1), callback(2), callback(3), callback(4), callback((5)]` 로 쌓인다. 
stack은 마지막에 들어간게 먼저 나오는 구조 이므로 call stack의 상단에 있는  callback(5)이 먼저 실행된다. 

`console.log(---5---)`가 call stack에 들어가면서 먼저 실행되고, Promise 구문이 마이크로 테스크 큐에 들어가면서 다음으로 실행되고 `console.log(--5--)` 를 출력한다.  마지막으로 태스크 큐에 들어간 setTimeout안의 로그 `console.log(-5-)`가 실행된다. 

이렇게 차례대로 

---5---
--5--
-5-
---4---
--4--
-4-
---3---
--3--
-3-
---2---
--2--
-2-
---1---
--1--
-1-
---0---
--0--
-0-

가 출력된다.

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`timer(5)`는 입력된 숫자(초)만큼 뒤에 특정 숫자를 세 번 출력하는 코드가 `setTimeout`으로 감싸져 있다.

`callback` 함수 내부의 `setTimeout`와 `Promise.resolve().then()`, `console.log` 동작으로 구분할 수 있다. 그리고 내부의 `console.log`는 즉시 실행되고, `Promise`는 마이크로태스크 큐에 추가되어 태스크 큐보다 우선되므로 실행되는 순서는 아래와 같다.

1. `---${i}---`
2. `--${i}--`
3. `-${i}-`

즉 `5`가 위의 순서대로 3번, `4`가 1초 뒤 위의 순서대로 3번, ... `0`이 5초 뒤 위의 순서대로 3번 출력된다.

</div>
</details>
