### ISSUE TITLE
[1장][동호] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by khakhiD** [KJ-StudyWithMe/modern-react-deep-dive#12]
### 퀴즈

1. 자바스크립트 언어의 데이터 타입 분류인 원시 타입(Primitive)과 객체 타입(Object/Reference)의 차이점이 무엇인가요?

<br />

2. 다음 중 `typeof`의 결과값이 다른 것은?
    - `typeof{}`
    - `typeof null`
    - `typeof []`
    - `typeof function(){}`
    - `typeof new Number(1)`
 
<br />

3. 다음 코드 실행 시 예상되는 출력 값을 답해주세요.
    ```js
    console.log(hi);
    var hi = 'hi';
    ```

<br />

4. 다음 코드 실행 시 예상되는 출력 값을 답해주세요.
    ```js
    const arr1 = [1, 2, 3];
    const arr2 = [];
    let currentValue = 0;
    for (const item of arr1) {
      currentValue = item;
      arr2.push(function () {
        console.log(currentValue);
      });
    }
    arr2[1]();
    ```

<br />

5. 다음 코드 실행 시 예상되는 `result`의 값을 답해주세요.
    ```js
    const arr = [1, undefined, 3, 4];
    const [x, y=10, ...rest1] = arr;
    const result = y + rest1[0];
    ```

### 답

<details>
<summary>정답</summary>
<div markdown="1">

1. **값의 저장 방식**이 다르다.
  원시 타입은 불변 형태로 변수 할당 시점에 메모리에 저장되고, 객체(참조) 타입은 가변 형태로 저장되며 복사해도 실제 값이 아닌 객체의 참조 값을 전달한다.

<br />

2. `typeof function(){}`의 결과는 `function` (나머지는 모두 `object`)

<br />

3. **`undefined`**
   호이스팅으로 인해 코드는 아래와 같이 해석된다.
   ```js
   var hi;
   console.log(hi); // undefined
   hi = 'hi';


<br />


4. `3`


<br />

5. `13`

</div>
</details>


### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 원시타입은 불변의 값을 메모리에 할당한다. 따라서 두 변수에 동일한 원시 데이터를 할당하면 두 변수는 동일하다고 판단된다.  

반면 객체 타입은 값을 참조하는 메모리 주소를 메모리에 할당한다. 따라서 객체 타입 데이를 복사하면 참조 값을 전달하기 때문에 두 변수는 동일한 메모리를 참조해 동등하다고 판단된다. 다만 보기에는 같은 두 개의 객체를 두 변수에 각각 할당하면 둘은 별도의 메모리 주소를 갖게 되므로 다르다고 판단된다.

2. `typeof new Number(1)` - 숫자를 반환해서 얘만 number고 다른 건 다 객체 타입?
3. `undefined`
4. `2`
5. 13
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 가장 큰 차이점은 값을 저장하는 방식이다. 원시타입은 값 그대로를 저장하지만 객체타입은 참조값을 저장하기 때문이다. <br />
2. typeof new Number(1)  <br />
3. undefined  <br />
4. 2 ...???? 호출됐을때가 아니라 선언되었을때의 값을 기억하니까..??  <br />
5. 13??????
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 자바스크립트 언어의 데이터 타입 분류인 원시 타입(Primitive)과 객체 타입(Object/Reference)의 차이점이 무엇인가요?
원시 타입의 경우 각각 다른 식별자에 할당되더라도 값이 동일하다면 동등 연산자로 비교했을 때 `true` 를 반환합니다.  
객체 타입의 경우에는 내부에 존재하는 키와 값이 모두 동일하다고 하더라도 값이 할당되는 시점에 새로운 객체를 만든다면 동등 연산자로 비교해도 `false` 를 반환합니다.

2. 다음 중 typeof의 결과값이 다른 것은?
(4번)

typeof{} Object
typeof null Object
typeof [] Object
typeof function(){} Function
typeof new Number(1) Object



3. 다음 코드 실행 시 예상되는 출력 값을 답해주세요.
undefined

(소스코드 평가 단계에서 실행 컨텍스트를 생성할 때, var 키워드로 선언한 변수의 경우 식별자 선언과 undefined로의 초기화가 동시에 발생하기 때문)

4. 다음 코드 실행 시 예상되는 출력 값을 답해주세요.
3

(currentValue는 최상위 스코프에 선언되어 있고, for 루프를 반복할 때마다 최상위 스코프의 currentValue 값을 할당하고 있습니다.
따라서 arr2 배열의 원소로 들어간 함수 내부에서 가리키는 currentValue는 최상위 스코프의 currentValue를 가리키므로 맨 마지막으로 할당된 3이 결과입니다.)

5. 다음 코드 실행 시 예상되는 result의 값을 답해주세요.
13

(arr 배열을 구조분해할당 하고 있습니다.
단, 2번째 요소인 y는 새로운 값 10을 할당하고, arr 배열에서 1번 인덱스 뒤의 모든 요소를 전개 연산자로 새로운 rest를 만들어냈는데, 첫 번째 요소는 기존 arr 배열의 3번 인덱스 값인 3이 되기 때문입니다.)

</div>
</details>

**Comment by jkea1** [comment]
1. 자바스크립트 언어의 데이터 타입 분류인 원시 타입(Primitive)과 객체 타입(Object/Reference)의 차이점이 무엇인가요?
- 원시 타입 : 변수에 원시 타입이 할당되면, 값에 의한 전달이 일어 나며 . 그 값은 불변 형태로 저장된다. 또한 이 값은 할당 시점에 메모리 영역을 차지한다. 
- 객체 타입 : 값을 저장하는 것이 아니라 참조를 저장한다. 원시 값과 다르게 변경 가능한 형태로 저장한다. 

2. 다음 중 typeof의 결과값이 다른 것은?
`function(){ }`

<img width="208" alt="Screenshot 2024-04-19 at 8 26 11 PM" src="https://github.com/KJ-StudyWithMe/modern-react-deep-dive/assets/99384699/adcaf773-43fa-4611-84e7-46a8dc1b71d5">

3. 호이스팅으로 `undefined`가 출력된다. 

4. `arr2[1]()` =>` arr2 의 두번째 값 실행`
처음에 2라고 생각 했는데 `currentValue`가 최상단에 선언되어 있는 것을 확인.
가장 마지막 값인 3이 currentValue에 할당 됨을 예상할 수 있음. 그래서 3이다. 

5. 
```
const arr = [1, undefined, 3, 4];
const [x, y=10, ...rest1] = arr;
const result = y + rest1[0];
```

`rest1 = [3, 4]` 이고 result = 10 + 3 = 13 이다.

**Comment by bbearcookie** [comment]
4번 문제에서 두 가지 핵심 개념이 포함된 좋은 문제네요!!

> 1. 원시 타입 vs 참조 타입
> 2. 스코프와 클로저

```js
const arr1 = [1, 2, 3];
const arr2 = [];
let currentValue = 0;
for (const item of arr1) {
  currentValue = item;
  arr2.push(currentValue); // 이렇게 원시 타입을 push 하면
}
arr2[1]; // 여기서 2가 됨!
```

```js
const arr1 = [1, 2, 3];
const arr2 = [];
let currentValue = 0;
for (const item of arr1) {
  let currentValue = item; // 이렇게 각각의 루프 블록 스코프에서 새로운 변수를 선언하면
  arr2.push(function () {
    console.log(currentValue);
  });
}
arr2[1](); // 여기서 2가 됨!
```
