### ISSUE TITLE
[2장][상훈] 리액트 핵심 요소 깊게 살펴보기

### ISSUE THREAD

**Issue by bbearcookie** [KJ-StudyWithMe/modern-react-deep-dive#15]
### 퀴즈

1. useEffect로 표현할 수 있는 클래스 컴포넌트의 라이프 사이클 메소드는 어떤 게 있나요?
2. useEffect와 useLayoutEffect의 차이점에 대해 설명해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1. useEffect로 표현할 수 있는 클래스 컴포넌트의 라이프 사이클 메소드는 어떤 게 있나요?
- componentDidMount: 컴포넌트 마운트 이후 최초로 실행되는 effect 콜백
- componentDidUpdate: 컴포넌트가 리렌더링되고 effect의 의존성 배열이 변경되었을 때 실행되는 effect 콜백
- componentWillUnmount: 컴포넌트가 리렌더링되고 effect의 의존성 배열이 변경되었을 때 실행되는 effect 콜백이 반환하는 클린업 함수

2. useEffect와 useLayoutEffect의 차이점에 대해 설명해주세요.
useEffect로 등록한 콜백 함수는 커밋 단계에서 변경한 DOM이 화면에 업데이트 된 이후에 실행됩니다.
즉, effect 콜백에서 화면 UI에 변화를 주는 동작을 수행한다면, 사용자는 render(UI 바뀜) -> effect -> render(UI 바뀜) 순서로 실행되면서 화면이 두 번 변경되어 보이는 불쾌한 경험을 할 수 있습니다.

그런데 useLayoutEffect는 커밋 단계에서 변경한 DOM을 화면에 그리는 것을 막고, layoutEffect 콜백을 먼저 수행합니다. 따라서 사용자는 render(UI 안 바뀜) -> layoutEffect -> render(UI 바뀜)

대신, useLayoutEffect 콜백에서 수행되는 연산이 길어진다면 브라우저를 잠시동안 멈추게 하는 불쾌한 경험을 줄 수 있으니 유의해야 합니다.

### 예제 소스 코드

```js
import { useEffect, useLayoutEffect, useState } from 'react';

const MyEffect = () => {
  const [title, setTitle] = useState('');

  useLayoutEffect(() => {
    console.log('useLayoutEffect');
    for (let i = 0; i < 1000000000; i++) {}
    setTitle('Hello');
  }, []);

  useEffect(() => {
    console.log('useEffect');
    for (let i = 0; i < 1000000000; i++) {}
    setTitle('Bye');
  }, []);

  return <div>하이 {title}</div>;
};

export default MyEffect;

```

### effect 실행 결과 (브라우저는 안멈추는데, UI가 깜빡임)

![effect](https://github.com/KJ-StudyWithMe/modern-react-deep-dive/assets/50488780/c116e8fc-1385-4e1e-83a2-f6d7680b45dc)

### layoutEffect 실행 결과 (브라우저가 멈추지만, UI는 깜빡이지 않음)

![layouteffect](https://github.com/KJ-StudyWithMe/modern-react-deep-dive/assets/50488780/01a5ea71-7073-4f4c-aa1d-bb82bea4ce29)

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. componenDidmount, componentDidUpdate, componentWillUnmount
2. 동기 비동기?
</div>
</details>

**Comment by jkea1** [comment]
1. useEffect로 표현할 수 있는 클래스 컴포넌트의 라이프 사이클 메소드는 어떤 게 있나요?
> 클래스 컴포넌트의 라이프 사이클 메소드 중에서 useEffect의 동작과 유사한 기능을 수행하는 메소드에는 무엇이 있는지를 물어 보는 질문으로 이해했습니다. (맞나요?)
- `componentDidMount` : 컴포넌트가 처음으로 렌더링 될 때 실행됩니다. 
- `componentDidUpdate` : useEffect의 두 번째 인수로 전달되는 의존성 배열을 사용하여 특정 state나 props의 변경을 감지하거나 리렌더링시 작동하는 `useEffect`의 역할을 `componentDidUpdate`(컴포넌트가 업데이트가 일어난 이후 바로 실행된다.)가 수행 할 수 있습니다. 

- `componentWillUnmount`는 생각하지 못했습니다. 
  -  : `componentWillUnmount`는 컴포넌트가 언마운트되거나 더 이상 사용되지 않기 직전에 호출됩니다. "useEffect" 훅은 해당 효과가 사라질 때 실행할 클린업 함수를 반환(return)하는데 componentWillUnmount`가 이 작업와 유사한 작업을 함을 알 수 있었습니다. 
  
2. useEffect와 useLayoutEffect의 차이점에 대해 설명해주세요.
- useEffect
  - useEffect는 컴포넌트들이 render 와 paint 된 후 실행됩니다. paint 된 후 실행되기 때문에, useEffect 내부에 dom 에 영향을 주는 코드가 있을 경우 사용자 입장에서는 화면의 깜빡임을 보게됩니다.
  > render : DOM Tree 를 구성하기 위해 각 엘리먼트의 스타일 속성을 계산하는 과정
  > paint : 실제 스크린에 Layout을 표시하고 업데이트하는 과정 
- useLayoutEffect
  - useLayoutEffect 는 컴포넌트들이 render 된 후 실행되며, 그 이후에 paint 가 됩니다. paint 가 되기전에 실행되기 때문에 dom 을 조작하는 코드가 존재하더라도 사용자는 깜빡임을 경험하지 않습니다.

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. `componentDidMount`, `componentDidUpdate`, `componentWillUnMount`  
2. useEffect는 리페인팅 과정까지 모두 일어난 후에 작동하므로 사용자가 깜빡이는 현상을 볼 수 있다. 반면 useLayoutEffect는 렌더링 이후 리페인팅이 일어나기 전에 일어나므로 사용자가 깜빡임을 볼 수 없다. 따라서 시각적인 변경이 일어나게 될 로직은 useEffect가 아닌 useLayoutEffect에 작성하는 것이 좋다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. **`componentDidMount`, `componentDidUpdate`, `componentWillUnmount`**
2. **useEffect와 useLayoutEffect의 차이점**
    두 hook은 모두 리액트 함수형 컴포넌트에서 사이드 이펙트를 처리하기 위해 사용되지만, 렌더링 사이클에서 언제 실행되는지 차이가 있다. useEffect는 화면 렌더링 후에 비동기적으로 실행되며, useLayoutEffect는 화면 렌더링이 되기 전에 동기적으로 실행된다. 따라서 useLayoutEffect의 경우 등록한 작업이 끝날 때까지 렌더링을 하지 않아야 하는 작업에 사용할 수 있다. 하지만 이 작업이 길어지는 경우 화면이 그려지는 데 오랜 시간이 걸려 사용자 경험이 떨어질 수 있다.


</div>
</details>
