### ISSUE TITLE
[2장][민희] 리액트 핵심요소 깊게 살펴보기

### ISSUE THREAD

**Issue by leeminhee119** [KJ-StudyWithMe/modern-react-deep-dive#17]
### 퀴즈

1. 가상 DOM이 필요한 이유를 설명해주세요.
2. 리액트는 모든 컴포넌트의 실행 결과 값을 가상 DOM과 비교하고, 감지된 모든 변경사항을 실제 DOM에 반영한다. (O/X)

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. 브라우저의 렌더링 비용과 개발자의 수고를 줄여주기 위해 사용된다. 사용자 인터랙션이 많을 때는 레이아웃 이후에 리페인팅 과정까지 수반되고, 자식 요소까지도 변경해야 해서 많은 비용이 들어간다. 또한 SPA에서도 하나의 페이지에서 위치를 계속 재계산해야 하므로 비용이 크다.   
리액트는 이러한 비용과 수고를 줄이기 위해 메모리상에서 가상 DOM을 이용해 값을 비교하고, 변경사항들을 수집하여 실제 DOM에 적용하기 때문에 브라우저는 별도의 계산 없이 결과만 받아 렌더링하면 된다.  

2. X, 리액트18부터는 렌더 단계가 비동기로 작동해 렌더링 작업들 간 우선순위를 정할 수 있고, 특정 렌더링은 중단하거나 필요없다고 판단되는 경우 폐기할 수도 있다. 따라서 감지된 모든 변경사항이 실제 DOM에 반영되는 것은 아니다. 즉, 리액트의 렌더링이 일어난다고 반드시 DOM 업데이트가 일어나는 것은 아니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1.  X
React 18 버전 이전에는 렌더 단계에서 변경 사항을 계산했을때(재조정) 변경 사항이 없으면 커밋 단계에서 멈춥니다.(이 또한 리액트의 렌더링이다.) 변경 사항이 있다면 커밋 단계까지 수행에 브라우저의 DOM에서 리렌더링이 일어납니다. 하지만 React 18 부터는 비동기 렌더링(동시성 렌더링)이 도입되어 렌더 단계가 비동기적으로 작동해 특정 렌더링의 우선순위를 낮추거나, 필요하다면 중단하거나 재시작 혹은 포기할 수 있습니다. 즉, 감지된 변경 사항이 중단되거나 포기 될 수 있으므로  '모든 변경사항을 실제 DOM에 반영한다.' 라는 말은 틀립니다.

> 질문!
리액트는 모든 컴포넌트의 실행 결과 값을 가상 DOM과 비교하는 문장은 맞나요?

2. 리액트의 가상 DOM은 웹페이지가 표시해야 할 DOM을 일단 메모리에 저장하고 리액트가 실제 변경에 대한 준비가 완료됐을 때 실제 브라우저의 DOM에 반영합니다. 이렇게 DOM 계산을 브라우저가 아닌 메모리에서 계산하는 과정을 한 번 거치게 됨으로써 실제로 여러번 발생했을 랜더링 비용(리액트 렌더링 비용(랜더:재조정 + 커밋) + 브라우저 렌더링 비용(리레이아웃+리페인트))을 최소화 함으로써 브라우저와 개발자의 부담을 덜 수 있습니다.

**Comment by leeminhee119** [comment]
@jkea1 
> 질문!
> 리액트는 모든 컴포넌트의 실행 결과 값을 가상 DOM과 비교하는 문장은 맞나요?  

사실 저도 이 부분 아직 헷갈리기는 한데, 저는 ~~렌더 단계에서 컴포넌트를 실행시키고 그 결과를 가상 DOM과 비교해 변경사항이 필요한지 체크하는 건 모든 컴포넌트에 대해서 이루어지는 걸로 이해했습니다.~~ 토의 시간에 같이 얘기해보면 좋을 것 같아요 !!

음.. 최초 렌더링이 아니라면 모든 컴포넌트를 순회하지는 않고 트리거를 발생시킨 (상태 변화가 일어난) 컴포넌트부터 비교를 하는 것 같긴 합니다..! ([참고](https://ko.react.dev/learn/render-and-commit#step-2-react-renders-your-components))

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 가상 DOM이 필요한 이유를 설명해주세요.

리액트는 개발자로 하여금 컴포넌트가 나타내야 할 UI를 선언적으로 작성할 수 있도록 도와주는 라이브러리인데, 이러한 개발 방식을 제공하면서 최적화도 어느정도 챙기기 위해서 가상 DOM이 필요합니다.

원래 PHP나 JSP같이 서버 단에서 템플릿 언어로 새로운 페이지를 그려줬던 MPA에서는 클라이언트에서 화면을 조작해야 할 일이 많지 않았기에 DOM API나 jQuery 라이브러리로도 충분히 복잡하지 않게 관리할 수 있었는데

점차 ajax 요청으로 얻어온 응답으로 화면을 조작하거나, 사용자 인터랙션으로 클라이언트 단에서 라우팅을 변경하는 SPA가 활발하게 적용되면서 클라이언트 단 로직이 복잡해졌습니다.
(리액트가 등장하기 전에 Underscore.js나 Backbone.js같은 MV* 패턴도 있었다고 하는데 이 부분은 아직 잘 모르겠네요..)

그래서 변경된 데이터에 따라서 언제 DOM 요소를 추가할 것이고, 어떤 DOM 요소를 업데이트할 것인지 등 관리하기가 점점 복잡해졌는데, 리액트는 개발자가 이런 고민을 할 필요 없이 그냥 컴포넌트가 보여줘야 할 UI만 JSX문법을 활용해서 표현하면 알아서 가상DOM에 먼저 그려놓고, 실제로 DOM에 반영해야 할 부분만 적용하는 방식으로 동작하기에 가상 DOM이 필요합니다.
(만약 이런 매커니즘에 가상DOM이 없다면, 컴포넌트가 리렌더링될 때마다 UI 트리에 해당하는 DOM 요소를 새로 생성하는 등의 비효율이 발생할 것입니다.)

2. 리액트는 모든 컴포넌트의 실행 결과 값을 가상 DOM과 비교하고, 감지된 모든 변경사항을 실제 DOM에 반영한다.
정답: X.

리액트는 Render 단계에서 재조정 과정을 통해 파이버 트리를 업데이트하고, 변경된 노드만 비교해서 실제 DOM에 반영하는 Commit 단계를 수행합니다.

그리고 React.memo 고차함수나 shouldComponentUpdate 메소드를 통해 특정 컴포넌트의 리렌더링을 스킵할 수 있습니다.


</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 사용자의 인터랙션이 많은 경우, 웹페이지가 변경됨에 따라 레이아웃이 변경되고 리페인팅이 발생하게 되는데 이는 비효율적이다. 이러한 문제를 해결하기 위해 나온것이 가상 돔이다. 가상돔은 말그대로 가상이란 뜻으로 변경사항이 발생하면 바로 돔에 적용되는것이 아니라 bactching을 통해 변경사항을 한번에 적용하는 등 효율적으로 작동한다. 
2. x
</div>
</details>
