### ISSUE TITLE
[2장][진경] 리액트 핵심요소 깊게 살펴보기

### ISSUE THREAD

**Issue by jkea1** [KJ-StudyWithMe/modern-react-deep-dive#19]
### 퀴즈

B 컴포넌트의 버튼을 눌러 counter 변수를 업데이트 한다고 했을 때, A, B, C, D 컴포넌트 중 리랜더링이 일어나는 컴포넌트는 어떤 것이고 각각 리 랜더링이 일어난 이유는 무엇인지 설명하세요. 

```
import { useState } from 'react'

export default function A() {
  return (
    <div className="App">
      <h1>Hello React!</h1>
      <B />
    </div>
  )
}

function B() {
  const [counter, setCounter] = useState(0)

  function handleButtonClick() {
    setCounter((prev) => prev + 1)
  }

  return (
    <>
      <label>
        <C number={counter} />
      </label>
      <button onClick={handleButtonClick}>+</button>
    </>
  )
}

function C({ number }) {
  return (
    <div>
      {number} <D />
    </div>
  )
}

function D() {
  return <>리액트 재밌다!</>
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
B : setter가 실행되었기 때문입니다. 
C : props가 변경되었기 때문입니다. 
D : 부모 컴포넌트가 렌더링 되었기 때문입니다. 
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
정답: B, C, D 컴포넌트에 리렌더링이 발생합니다.
이유: B의 지역 상태를 변경하는 dispatcher를 실행하면 B가 리렌더링 되는데, 리액트에서는 부모 컴포넌트가 업데이트되면 React.memo 고차함수로 래핑하지 않는 이상 모든 자식 컴포넌트가 리렌더링되기 때문입니다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
B,C => setState로 인한 리렌더링 발생,  C는 부모 컴포넌트로 받는 props가 변경되어 리렌더링 
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

B - state가 변경되므로 리렌더링된다.  
C - 부모B가 리렌더링되고 props도 변경되므로 리렌더링된다.  
D - 부모C가 리렌더링되므로 리렌더링된다.  
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

**B, C, D 컴포넌트가 리렌더링된다.**
- B 컴포넌트의 경우 state가 변경되었으므로 리렌더링된다.
- C 컴포넌트의 경우 부모 컴포넌트와 함께 리렌더링된다. 또한, props가 변경된 것이 리렌더링 조건에 포함된다.
- D 컴포넌트의 경우 부모 컴포넌트와 함께 리렌더링된다.


</div>
</details>
