### ISSUE TITLE
[2장][동호] 리액트 핵심 요소 깊게 살펴보기

### ISSUE THREAD

**Issue by khakhiD** [KJ-StudyWithMe/modern-react-deep-dive#21]
### 퀴즈

1. 리액트에서 마운트되어 있는 컴포넌트 내부 값에 변경이 일어나 리렌더링이 진행된다고 가정할 때, 실행될 수 있는 컴포넌트 생명주기 메서드를 보기에서 고르고 작동 순서를 올바르게 나열해주세요.
    
    **[보기]**
    `render()`, `shouldComponentUpdate()`, `componentDidUpdate()`, `getDerivedStateFromProps()`, `getSanpshotBeforeUpdate()`, `componentDidMount()`, `componentWillUnmount()`

<br />

2. 리액트 메모이제이션에 대한 견해 중 '모조리 메모리제이션해 버리자'는 주장이 제시하는 근거를 간략히 설명해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1. 답

  `getDerivedStateFromProps()` -> `shouldComponentUpdate()` -> `render()` -> `getSnapshotBeforeUpdate()`
 -> (React DOM 및 refs 업데이트) -> `componentDidUpdate()`

![image](https://github.com/KJ-StudyWithMe/modern-react-deep-dive/assets/74141521/89ff61b2-6d17-4ed4-9052-73657c4d93ed)

<br />

2. "`메모이제이션으로 얻는 비용 < 메모이제이션하지 않아 발생하는 문제에 대한 비용`일 가능성이 높기 때문에"
    메모이제이션의 얕은 비교가 발생하며 지불해야 하는 비용(즉, 값 비교 작업과 메모리 차지)보다, 갈수록 복잡해질 가능성이 높은 컴포넌트의 내부 로직을 재실행하고 자식 컴포넌트에도 그 영향을 끼치는 작업이 높은 비용을 감수해야 할 가능성이 더 높다.

    (굳이 제가 제시한 답이 아니어도 어느 정도의 견해가 들어갔다면 정답 처리 하셔도 될 것 같습니다.)

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 리액트에서 마운트되어 있는 컴포넌트 내부 값에 변경이 일어나 리렌더링이 진행된다고 가정할 때, 실행될 수 있는 컴포넌트 생명주기 메서드를 보기에서 고르고 작동 순서를 올바르게 나열해주세요.

getDerivedStateFromProps -> shouldComponentUpdate -> render -> getSanpshotBeforeUpdate -> componentDidUpdate

2. 리액트 메모이제이션에 대한 견해 중 '모조리 메모리제이션해 버리자'는 주장이 제시하는 근거를 간략히 설명해주세요.

- 리액트 렌더링의 비용은 비싸고, 메모이제이션은 props의 얕은 비교만 수행하면 되기 때문
- 프로젝트를 진행하다보면 어떤 부분에 최적화를 할 것인지 신경 쓰기가 쉽지 않은데, 그냥 모두 메모이제이션 해서 최적화에 크게 신경 쓰지 않으면서도 평균적으로 유리하다고 보기 때문

</div>
</details>

**Comment by jkea1** [comment]
1. getDerivedStateFromProps() -> shouldComponentUpdate() -> render() -> getSnapshotBeforeUpdate()
-> (React DOM 및 refs 업데이트) -> componentDidUpdate()

2. 메모이제이션을 했을때 예를 들어, `memo`를 이용한다고 했을 때 props 에 대한 얕은 비교를 해야 한다는 비용(1)이 들고 `useMemo`와 `useCallback`을 사용할 시에는 의존성 배열을 비교하는 작업 등의 비용이 드는데, 메모이제이션을 안 했을 때 생기는 비용(2)(1. 렌더링을 함으로써 발생하는 비용, 2. 컴포넌트 내부의 복잡한 로직의 재실행, 3. 자식 컴포넌트의 재 렌더링, 4. 리액트에서 구 트리와 신규 트리를 비교하는 비용)이 드는데 비용 1 < 2 라고 여겨져서 무조건 메모이제이션해야 한다고 주장한다.

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 모르겠습니다!
2. 렌더링에 드는 비용보다 모조리 메모이제이션하는게 더 싸서
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. getDerivedStateFromProps -> shouldComponentUpdate -> render -> getSnapshotBeforeUpdate -> componentDidUpdate
2. 리액트는 어차피 재조정 알고리즘을 위해 이전 렌더링 결과를 메모리 상에 저장해둔다. memo를 사용하지 않더라도 메모리는 차지하기 때문에 memo 를 사용했을 때 실제로 지불하는 비용은 props의 얕은 비교뿐이다. 또한 useMemo, useCallback은 메모하지 않으면 매번 새로운 객체를 생성하고 참조가 달라진다. 만약 useEffect같은 훅의 의존성 배열에 이 참조값이 쓰인다면 해당 훅에도 매번 영향을 주기때문에 메모이제이션을 해야 고정값을 안정적으로 사용할 수 있게 한다.
</div>
</details>
