### ISSUE TITLE
[2장][다은] 리액트 핵심 요소 깊게 살펴보기

### ISSUE THREAD

**Issue by GBAJS754** [KJ-StudyWithMe/modern-react-deep-dive#22]
### 퀴즈

```jsx
import React from 'react'
  interface Props {
  user: string
  ｝

export function FunctionalComponent (props: Props) {
  const showMessage = () => {
    alert('Hello ' + props.user)
  ｝
  const handleClick = () = {
    setTimeout (showMessage, 3000)
  ｝
  return cbutton onClick={handleClick}>FoLLow/button>
｝

export class ClassComponent extends React.Component<Props, {}> {
  private showMessage = () => {
    alert('Hello ' + this.props.user)
  }
  private handleClick = () => {
    setTimeout (this.showMessage, 3000)
  }
  public render() {
    return <button onClick={this.handleClick}>Follow</button>
  ｝
 }
```

함수 컴포넌트는 렌더링된 값을 고정하고 클래스 컴포넌트는 그렇지 못하는 이유에 대해 설명해주세요!
추가로 위의 코드를 참고하여 클래스 컴포넌트의 this값을 고정하는 방법을 제시해주세요!

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
이유 : 클래스 컴포넌트는 props를 this에서 가져오기때문이다! <br>
방법1. render에 필요한 값을 넣는 방법
<div>

```jsx
render(){
  const props = this.props
   const showMessage = () => {
      alert('Hello ' + this.props.user)
    }
   const handleClick = () => {
      setTimeout (this.showMessage, 3000)
    }
  return <button onClick={this.handleClick}>Follow</button>
}
```
</div>
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
원인: 클래스 컴포넌트의 props는 인스턴스 내부의 프로퍼티로 관리되는데, 3초 뒤에 호출한 this는 이미 변경된 props를 가리키기 때문.
해결: call, apply, bind 등으로 this 고정..?
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

함수 컴포넌트는 렌더링이 호출된 그 시점의 state와 props 값을 스냅샷찍어 렌더링에 활용하지만, 클래스 컴포넌트는 state와 props가 변경 가능한 this(컴포넌트 인스턴스)에 바인딩되어있어 렌더링 시 변경된 값을 읽을 수 있다.
고정하는 법: this.props의 값을 미리 꺼내둔다.
```jsx
export class ClassComponent extends React.Component<Props, {}> {
  private showMessage = (name) => {
    alert('Hello ' + name)
  }
  private handleClick = () => {
	const {
		props: {user}
	} = this;
    setTimeout (this.showMessage(user), 3000)
  }
  public render() {
    return <button onClick={this.handleClick}>Follow</button>
  ｝
 }
```

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

클래스형 컴포넌트는 handleClick이 클래스의 메서드로 정의되어 있어 this.props에 접근할 수 있기 때문이다.

1. bind 메서드를 사용하여 메서드 내의 this 값을 고정
2. 화살표 함수를 사용하여 외부 스코프(클래스 컴포넌트 인스턴스)의 this값으로 고정

</div>
</details>

**Comment by jkea1** [comment]
이유 : 클래스 컴포넌트는 props를 this에서 가져오기 때문입니다.

render에 필요한 값을 넣는다
```
render(){
  const props = this.props
   const showMessage = () => {
      alert('Hello ' + this.props.user)
    }
   const handleClick = () => {
      setTimeout (this.showMessage, 3000)
    }
  return <button onClick={this.handleClick}>Follow</button>
}
```
