### ISSUE TITLE
[3장][다은] 리액트 훅 깊게 살펴보기

### ISSUE THREAD

**Issue by GBAJS754** [KJ-StudyWithMe/modern-react-deep-dive#25]
### 퀴즈

React.memo와 React.useMemo의 차이점에 대해 설명해주세요!

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
useMemo를 사용할 경우 값을 반환받기때문에 JSX함수 방식이 아닌 {}를 사용한 할당식을 사용한다는 차이점이 있다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

React.memo는 컴포넌트를 메모이제이션한다. props가 변경되지 않는 한 부모가 리렌더링되더라도 리렌더링시키지 않는다.
useMemo는 값을 계산하는 함수를 전달하면 해당 값을 메모이제이션한다. 의존성 배열의 요소가 변경되지 않으면 다시 연산하지 않고 저장된 값을 불러온다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`React.memo`와 `useMemo`는 모두 메모이제이션을 통한 성능 최적화를 위한 리액트 API 일종입니다. 이전의 값을 메모리에 저장하여 기억하고, 변경 사항이 있을 때만 리렌더링이 발생하도록 하여 불필요한 렌더링을 방지합니다.

`React.memo`의 경우 함수형 컴포넌트의 전체 결과값을 메모이제이션하고, `useMemo`의 경우 복잡한 연산을 하는 함수의 특정 값을 메모이제이션한다. useMemo는 값을 반환하므로 JSX에서 호출하는 것이 아니라 값을 변수에 할당하여 사용한다.

</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">    
`React.momo`와 `useMemo` 모두 메모이제이션을 통해 렌더링 성능을 최적화하는 리액트의 API의 일종이다.

하지만 `React.momo`는 고차 컴포넌트로 렌더링하기 앞서 props를 비교해 이전과 props가 같다면 렌더링 자체를 생략하고 이전에 기억해 둔 컴포넌트를 반환한다.
`useMemo`는 비용이 큰 연산에 대한 결과값을 저장(메모이제이션)해 두고, 저장된 값을 반환하는 훅이다. useMemo를 이용해서 컴포넌트도 기억할 수 있지만 이렇게 되면 {}을 이용한 할당식을 이용해야 한다. 고로 컴포넌트를 기억할때는 `React.momo`를 이용하는 게 현명하다. 
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. React.memo 는 컴포넌트를 메모이제이션하는 HoC입니다. (컴포넌트의 인자가 변경되지 않으면 렌더링 과정에서 스킵합니다.)
2. useMemo 는 값을 메모이제이션하는 Hook입니다. (의존성 배열이 변경되지 않는 한 첫 번째 인자로 전달한 콜백을 실행한 결과를 재활용합니다.)
</div>
</details>
