### ISSUE TITLE
[3장][정진경] 리액트 훅 깊게 살펴보기 

### ISSUE THREAD

**Issue by jkea1** [KJ-StudyWithMe/modern-react-deep-dive#29]
### 퀴즈

아래의 코드를 바탕으로 빈칸을 채우세요. 빈칸에는 `콘솔 탭에 찍히는 로그 내용` 혹은 `리렌더링` 혹은 `아무일도 없다` 가 들어갑니다.

[초기 렌더링] => ` ` => [버튼이 아닌 그냥 클릭시]=> ` ` => [버튼 click] => ` ` => ` ` => ` ` => ` ` => [버튼이 아닌 그냥 클릭 시] => ` `  => [버튼 click] => ` ` => ` ` => ` ` => ` `

```
function App() {
  const [count, setCounter] = useState(0)

  function handleButtonClick() {
    setCounter((prev) => prev + 1)
  }

  useEffect(() => {
    console.log('effect 확인!')

    function addMouseEvent() {
      console.log('event 감지 effect 실행', count)
    }

    window.addEventListener('click', addMouseEvent)

    return () => {
      console.log('클린업 함수 실행', count)

      window.removeEventListener('click', addMouseEvent)
    }
  }, [count])

  return (
    <div style={{ height: '500px' }}>
      <h1>{count}</h1>
      <button onClick={handleButtonClick}>button</button>
    </div>
  )
}
  ```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
[초기 렌더링] => `effect 확인!` => [버튼이 아닌 그냥 클릭시]=> 'event 감지 effect 실행 0' => [버튼 click] => [리렌더링] => `클린업 함수 실행 0` => `effect 확인!` => `event 감지 effect 실행 1` => [버튼이 아닌 그냥 클릭 시] => `event 감지 effect 실행 1` (eventListener가 window 객체에서 지워지지 않았기 때문에) => [버튼 click] => [리렌더링] => `클린업 함수 실행 1` => `effect 확인!` => `event 감지 effect 실행 2`

---

만약 클린업 함수가 없었더라면 
```
const [count, setCounter] = useState(0)

    function handleButtonClick() {
      setCounter((prev) => prev + 1)
    }

    useEffect(() => {
      console.log('effect 확인!', count)

      function addMouseEvent() {
        console.log('event 감지 effect 실행', count)
      }

      window.addEventListener('click', addMouseEvent)

    }, [count])

    return (
      <div style={{ height: '500px' }}>
        <h1>{count}</h1>
        <button onClick={handleButtonClick}>button</button>
      </div>
    )
```
위의 코드를 바탕으로 
[초기 렌더링] => `effect 확인! 0` => [버튼 click] => [리렌더링] => `effect 확인! 1` => `effect 감지 effect 실행 0` => `effect 감지 effect 실행 1` => [버튼 click] => [리렌더링] => `effect 확인! 2` => `effect 감지 effect 실행 0` => `effect 감지 effect 실행 1` => `effect 감지 effect 실행 2`
와 같이 실행됩니다. 

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

[초기 렌더링] => `effect 확인!`  => [버튼이 아닌 그냥 클릭시]=> `event 감지 effect 실행 0`  => [버튼 click] => `리렌더링`  => `클린업 함수 실행 0`  => `effect 확인!` _(클린업함수 실행으로 이벤트핸들러 제거된 상태이므로 해당 로그 먼저 출력 후 event 감지 ~ 출력)_  =>  `event 감지 effect 실행 1` => [버튼이 아닌 그냥 클릭 시] => `event 감지 effect 실행 1`  => [버튼 click] => `리렌더링`  => `클린업 함수 실행 1`  => `effect 확인!`  =>  `event 감지 effect 실행 2`

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

[초기 렌더링] => `effect 확인!`  =>
[버튼이 아닌 그냥 클릭시]=> `event 감지 effect 실행` `0`  =>
[버튼 click] => **리렌더링** => `클린업 함수 실행` `1` => `effect확인!`  =>  `event 감지 effect 실행` `1` => **아무일도없다**  =>
[버튼이 아닌 그냥 클릭 시] => `event 감지 effect 실행` `1`  =>
[버튼 click] => **리렌더링**  => `클린업 함수 실행` `1`  => `effect확인!`  =>  `event감지 effect 실행` `2`


</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
[초기 렌더링] => effect 확인! => [버튼이 아닌 그냥 클릭시]=> event 감지 effect 실행 0 => [버튼 click] => 리렌더링  => 클린업 함수 실행 0  => effect 확인!  => 아무일도 없다  => [버튼이 아닌 그냥 클릭 시] => event 감지 effect 실행 1  => [버튼 click] => 리렌더링  => 클린업 함수 실행 1  => effect 확인!  => event 감지 effect 실행 2
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
effect 확인 =>event 감지 effect 실행 0 =>리렌더링 => Effect 확인 => Event 감지 effect 실행 , 1 => 클린업 함수 실행, 0 => event 감지 effect 실행 1 => 리렌더링 => Effect 확인 => Event 감지 effect 실행 , 2 => 클린업 함수 실행, 1
</div>
</details>
