### ISSUE TITLE
[3장][동호] 리액트 훅 깊게 살펴보기

### ISSUE THREAD

**Issue by khakhiD** [KJ-StudyWithMe/modern-react-deep-dive#30]
### 퀴즈

1. 리액트 클래스형 컴포넌트에서 PureComponent와 Component의 차이점은 무엇이고, 함수형 컴포넌트에서는 PureComponent를 어떻게 대체할 수 있나요?

2. 아래 코드 예제에서 ChildComponent의 `<button>`이 눌릴 때의 렌더링 동작을 간단히 설명해주세요.
```jsx
const ChildComponent = memo(({ name, value, onChange }) => {
  useEffcet(() => {
    console.log('rendering!', name)
  })`
  
  return (
  <>
    <h1>
      {name} {value ? '켜짐' : '꺼짐'}
    </h1>
      <button onClick={onChange}>toggle</button>
  </>
  )
})

function App() {
  const [status1, setStatus1] = useState(false)
  const [status2, setStatus2] = useState(false)
  
  const toggle1 = () => {
    setStatus1(!status1)
  }
  
  const toggle2 = () => {
    setStatus2(!status2)
  }
  
  return (
  <>
    <ChildComponent name="1" value={status1} onChange={toggle1} />
    <ChildComponent name="2" value={status2} onChange={toggle2} />
  </>
  )
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. PureComponent는 `shouldComponentUpdate` 메서드를 내장하고 있어 **props와 state를 이전 props와 state와 비교하여 변경 여부를 얕은 비교로 판단하고, 변경이 있을 때만 컴포넌트를 리렌더링합니다**. 따라서 props와 state가 변경되지 않으면 리렌더링을 방지할 수 있어 성능을 향상시킬 수 있습니다. 반면 Component는 부모 컴포넌트가 업데이트될 때마다 항상 리렌더링되어 불필요한 렌더링이 발생할 수 있습니다.
  **함수형 컴포넌트에서는 고차 컴포넌트인 `React.memo`를 활용**하여 대체할 수 있습니다.

2. ChildComponent에서 `<button>`이 눌리면 부모 컴포넌트의 setState를 호출하게 됩니다. 이는 부모 컴포넌트인 `App` 컴포넌트의 리렌더링을 발생시키고, `toggle1` 함수와 `toggle2` 함수를 새로 생성하기 때문에 새로운 주소값을 가집니다. 때문에 `onChange` 프로퍼티가 변경되고 ChildComponent는 리렌더링됩니다. 여기에 `useCallback` 훅을 사용하여 함수를 메모이제이션하여 함수를 새로 생성하지 않게 하여 ChildComponent의 리렌더링을 방지할 수 있습니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
### 1번 문제

PureComponent는 재조정 과정에서 State와 Props가 동일하다면 렌더링 과정을 생략할 수 있습니다. 함수 컴포넌트에서는 React.memo 고차 컴포넌트가 유사한 동작을 수행할 수 있으며, Props가 동일하다면 렌더링 과정을 생략합니다.

### 2번 문제

1. button을 클릭하면 부모로부터 전달받은 onChange 함수를 실행합니다.
2. 부모에서 전달한 onChange 함수의 내부에는 useState의 Dispatch 함수를 호출합니다. 따라서 리렌더링이 발생합니다.
3. 변경된 status 상태가 자식에게 전달되고, 자식 컴포넌트도 리렌더링이 발생합니다.

</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. state 업데이트 시 PureComponent는 state에 대해 얕은 비교를 하고 값이 다를 때만 리렌더링을 하지만, Component는 항상 리렌더링한다. 함수형 컴포넌트에는 React.memo를 쓰면 props에 대해 얕은 비교를 수행하여 값이 다를 때만 리렌더링을 한다.
2. 첫번째 ChildComponent의 버튼이 눌리면 toggle1이 실행되어 status1의 값이 업데이트되어 App이 리렌더링된다. 이때 두 번째 ChildComponent는 memo가 되어있지만 props로 전달된 toggle2가 새로 생성된 함수이기 때문에 props가 다르다고 판단해 리렌더링된다. 첫 번째 ChildComponent는 같은 이유로 + status1의 값도 변경되었기 때문에 역시 리렌더링된다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. memo를 사용하여 대체할수있으며 , pure는 불필요한 렌더링을 줄여줍니다.
2. memo를 사용하고 있기때문에 부모컴포넌트의 state가 변경되어도 자식 컴포넌트의 불필요한 렌더링을 방지해줍니다. 그러므로, state가 변경되어도 해당 state를 props로 받고있는 자식컴포넌트만 렌더링이 됩니다.
</div>
</details>

**Comment by jkea1** [comment]
1. PureComponent는 props와 state가 변경되지 않으면 리렌더링을 방지할 수 있어 성능을 향상시킬 수 있습니다. 반면 Component는 부모 컴포넌트가 업데이트될 때마다 항상 리렌더링되어 불필요한 렌더링이 발생할 수 있습니다. 함수형 컴포넌트에서는 고차 컴포넌트인 React.memo를 활용하여 PureComponent와 같은 효과를 낼 수 있습니다. 
2. <button>이 눌리면 setter가 호출 됩니다. setter가 동작하면 App 컴포넌트의 리렌더링이 발생합니다. 리렌더링으로 인데 toggle1, toggle2 함수는 새로운 주소값을 가지게 됩니다. ChildComponent의 onChange() prop 값이 바뀌게 되므로 ChildComponent도 리렌더링이 발생하게 됩니다.
