### ISSUE TITLE
[3장][상훈] 리액트 훅 깊게 살펴보기

### ISSUE THREAD

**Issue by bbearcookie** [KJ-StudyWithMe/modern-react-deep-dive#31]
### 퀴즈

훅을 반드시 최상단에 선언해야만 하는 이유를 설명해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
리액트는 렌더링 과정에서 훅을 실행한 순서로 각 훅에 대한 정보를 식별하기 때문입니다.
컴포넌트에서 훅이 사용되면, 훅이 사용되었던 순서대로 해당 컴포넌트의 파이버 노드의 memoizedState 프로퍼티에 연결 리스트로 저장됩니다.
그렇기 때문에 훅을 사용하는 순서를 고정하지 않으면, 각 훅의 정보가 꼬여버리는 현상이 발생하기 때문에 반드시 함수의 최상단에서 고정된 순서로 실행될 수 있음을 보장해야 합니다.
</div>
</details>

<details>
<summary>정답 보완</summary>
<div markdown="1">    
컴포넌트 내부에서 사용된 Hook의 순서를 반드시 보장해야 하기 때문입니다. (리액트는 렌더링 과정에서 훅을 실행한 순서로 각 훅에 대한 정보를 식별합니다.)
먼저, 리액트 컴포넌트는 reconciler에 의해서 Fiber 노드로 관리됩니다. 그리고 컴포넌트 내부에서 `useState` 와 같은 훅을 사용할 때 해당 컴포넌트가 처음으로 마운트 되었느냐, 혹은 이미 생성된 파이버 노드가 존재하여 업데이트 하는 상황이냐에 따라서 다른 함수가 불려집니다. 예를 들어 마운트 단계에서는 `mountState` 가 사용되고, 업데이트 단계에서는 `updateState` 가 사용됩니다.

그런데 `mountState` 내부에서는 `mountWorkInProgressHook` 이라는 함수를 호출하는데요, 여기에서는 새로운 Hook 객체를 생성한 뒤 기존 Fiber 노드의 `mountState` 프로퍼티로부터 가장 마지막에 새로운 Hook 객체를 연결 리스트로 연결하는 동작을 수행합니다. 그래서 컴포넌트가 첫 마운트됐을 때 내부에서 사용된 훅 객체를 생성한 뒤 고정된 순서로 연결해 놓는 것입니다.

이후에 컴포넌트가 리렌더링되면 `updateState` 가 호출되는데요, 그 내부에서는 `updateWorkInProgressHook` 이라는 함수가 사용됩니다. 이 함수에서는 Hook 객체를 새롭게 생성하는 것이 아니라, 이전에 생성됐던 Hook 객체를 그대로 활용합니다. 즉, 이전 Hook 객체가 연결되어 있던 순서를 그대로 재활용하게 됩니다.

따라서 컴포넌트에서 훅을 사용할 때 순서를 보장하지 못한다면, 특정 순서의 Hook 객체가 반드시 예상되는 객체라는 보장이 없기 때문에, 반드시 Hook을 컴포넌트나 커스텀 훅의 최상단에 선언하여 실행되는 순서가 고정되도록 해야 하는 것입니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

훅에 대한 정보 저장이 리액트 파이버 객체의 링크드 리스트에 담기면서, 저장된 순서에 따라 호출되기 때문이다.

**`re`**
**훅을 사용하는 순서를 고정하지 않으면 각 훅의 정보가 꼬여버리는 현상이 발생하기 때문에 반드시 함수의 최상단에서 고정된 순서로 실행될 수 있어야 한다.**

</div>
</details>

**Comment by jkea1** [comment]
236,7 참고 하자!

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

리액트의 각 훅은 파이버 객체 내에서 순서에 의존해 state나 effect의 결과에 대한 값을 저장하고 있기 때문에 파이버 객체의 링크드 리스트의 호출 순서에 따라 저장된다. 만약 조건문 등으로 인해 훅의 순서가 깨지게 되면 리액트는 에러를 발생시키기 때문에 항상 같은 순서가 보장되도록 컴포넌트 최상단에 훅을 선언해야 한다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
훅은 연결리스트로 구현되어있기때문에 순서를 보장하기위해서
</div>
</details>
