### ISSUE TITLE
[5장][상훈] 리액트와 상태 관리 라이브러리

### ISSUE THREAD

**Issue by bbearcookie** [KJ-StudyWithMe/modern-react-deep-dive#34]
### 퀴즈

1. 리액트가 관리하는 영역 바깥에 있는 데이터에 변화가 생겼을 때, 어떻게 리액트 컴포넌트가 변화를 감지하고 리렌더링하도록 유발할 수 있나요?
2. 1번 질문에 이어서 React 18 버전에 도입된 Concurrent Rendering을 사용하는 경우, 같은 데이터를 구독하고 있는 컴포넌트가 여러 개 있다고 했을 때 서로 다른 값이 UI에 그려지는 Tearing 현상이 발생할 수 있는데 이를 어떻게 해결할 수 있을까요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">
참고: https://youtu.be/oPfSC5bQPR8?si=lFljNkqAmoYD86LL&t=801

1. 리액트 외부의 모듈 레벨에서 Store를 관리하고 있다고 할 때, 해당 Store에 존재하는 값을 `useState` 로 보관하고, `useEffect` 를 사용해서 외부 상태를 리액트의 상태와 동기화 합니다.
2. `useEffect` 대신에 반드시 동기적으로 이펙트가 수행됨을 보장하는 `useSyncExternalStore` 를 사용합니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. `subscribe`함수를 만들면 된다. `subscribe`함수는 useState의 setState를 스토어의 변경된 값으로 실행시켜 리렌더링을 유도하는 함수이다. useEffect를 통해 store의 값이 변경되면 이 `subscribe`함수를 실행시켜 리렌더링을 유발한다.
2. `useSyncExternalStore`를 활용한다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. subscriber와 notify와 같은 함수를 통해 상태가 변화되었을 때 상태가 변화됨을 감지하여 callback을 실행하여 리렌더링을 유발한다?
2. useSyncExternalStore
 
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

모르겠어서 정답보고 유튭 정주행

<re>
참고: https://youtu.be/oPfSC5bQPR8?si=lFljNkqAmoYD86LL&t=801
리액트 외부의 모듈 레벨에서 Store를 관리하고 있다고 할 때, 해당 Store에 존재하는 값을 useState 로 보관하고, useEffect 를 사용해서 외부 상태를 리액트의 상태와 동기화 합니다.
useEffect 대신에 반드시 동기적으로 이펙트가 수행됨을 보장하는 useSyncExternalStore 를 사용합니다.


</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 리액트 외부의 모듈 레벨에서 데이터를 Store가 관리하고 있다고 할 때, 해당 Store에 존재하는 값을 state로서 useState로 관리하고, useEffect를 사용해서 변환를 감지하여 외부 상태를 리액트의 상태와 동기화 합니다.

2. `useEffect` 대신에 반드시 동기적으로 이펙트가 수행 됨을 보장하는 `useSyncExternalStore` 를 사용할 수 있습니다. 
</div>
</details>
