### ISSUE TITLE
[5장][다은] 리액트와 상태 관리 라이브러리 

### ISSUE THREAD

**Issue by GBAJS754** [KJ-StudyWithMe/modern-react-deep-dive#37]
### 퀴즈

1. FLUX 패턴의 4가지 요소를 적고 어떤 기능을 하는지 설명해주세요!
2. useState와 useReducer를 기반으로 하는 사용자 지정 훅의 한계점에 대해 적어주세요!

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1.
액션 : 어떠한 작업을 처리할 액션과 그 액션 발생시 함께 포함 시킬 데이터를 의미
디스패처 : 액션을 스토어에 보내는 역할
스토어 : 값과 상태를 변경할수있는 메서드를 가지고 있다.
뷰 : 리액트 컴포넌트에 해당하며 데이터를 가져와 화면을 렌더링하는 역할
2. 훅을 사용할때마다 컴포넌트 별로 초기화 되므로 컴포넌트에 따라 서로 다른 상태를 가지게된다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. FLUX 패턴의 네 가지 요소
`Action`: 어떠한 작업을 처리할 액션과 그 액션 발생 시 함께 포함시킬 데이터. 디스패처로 보낸다.
`Dispatcher`: 액션을 스토어에 보내는 역할. 콜백함수의 형태.
`Store`: 실제 상태에 따른 값 + 상태를 변경할 수 있는 메서드를 담고 있다. 액션의 타입에 따라 어떻게 변경할지 정의.
`View`: 리액트의 컴포넌트. 스토어에서 데이터를 가져와 렌더링. 뷰에서 사용자 이벤트에 의해 상태 업데이트 가능, 이 경우 뷰에서 액션을 호출해 디스패처로 보내게 된다.
2. useState, useReducer를 기반으로 하는 사용자 지정 훅은 관리하는 상태의 스코프가 지역 스코프라는 한계가 있다. 지역 상태이기 때문에 여러 컴포넌트에서 같은 훅을 사용하더라도 상태 값이 별개로 관리된다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. Flux 패턴의 4가지 요소 
    - Action: 작업을 처리하는 액션 + 액션 발생에 포함되는 데이터
    - Dispatcher: 액션을 스토어로 보내주는 역할
    - Store: 실제 상태에 따른 값과 상태를 변경할 수 있는 메서드를 가지고 있음
    - View: 리액트 컴포넌트, 스토어에서 만들어진 데이터로 화면을 렌더링
 
3. useState와 useReducer로 관리하는 상태 관리는 지역 상태라는 한계가 존재
  두 훅을 사용한 컴포넌트의 인스턴스가 바뀌면 상태도 바뀜


</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. Flux 패턴의 4가지 요소 
- Action : 어떤 작업을 처리할 액션과 액션 발생 시 포함시킬 데이터
- Dispatcher : 액션을 스토어에 보내는 역할을 한다.
- Store : 실제 상태에 따른 값과 상태를 변경할 수 있는 메서드를 가지고 있다.
- View : 리액트의 컴포넌트에 해당하는 부분으로, 스토어에서 만들어진 데이터를 가져와 화면을 렌더링하는 역할을 한다.
 
2. useState, useReducer를 기반으로 하는 커스텀 훅은 관리하는 상태의 스코프가 지역 스코프라는 한계가 있습니다. 지역 상태이기 때문에 여러 컴포넌트에서 같은 훅을 사용하더라도 각각의 상태 값이 별개로 관리됩니다.


</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. FLUX 패턴의 4가지 요소를 적고 어떤 기능을 하는지 설명해주세요!
- Action: 상태를 변경하려는 Action을 나타내는 요소입니다. type과, 변경하려고 할 payload를 담을 수 있습니다.
- Dispatcher: View로부터 Action을 전달 받으면, 변경해야 할 내용을 Store에게 전달합니다.
- Store: 상태가 보관되고 있는 요소입니다.
- View: UI를 표현하는 요소입니다. Store에 있는 데이터를 가지고 화면을 표현하기도 하고, Dispatcher에게 Action을 전파하여 상태 변경 요청을 하기도 합니다.

2. useState와 useReducer를 기반으로 하는 사용자 지정 훅의 한계점에 대해 적어주세요!
- 지역 상태를 갖고 있기에, 여러 컴포넌트 간 공유가 필요하면 상위 트리로 끌어올려야 하는 번거로움?
- 컴포넌트 별 다른 상태를 갖고 있기에, 예를 들어 SPA에서 페이지가 변경되었을 때 상태가 유지되지 않는 현상

</div>
</details>
