### ISSUE TITLE
[5장][민희] 리액트와 상태관리 라이브러리

### ISSUE THREAD

**Issue by leeminhee119** [KJ-StudyWithMe/modern-react-deep-dive#38]
### 퀴즈

Recoil, Jotai와 Zustand의 공통점, 각각의 간단한 특징과 차이점을 작성해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

### 셋의 공통점
- Redux와 달리 별도의 리액트 패키지를 설치하지 않아도 상태가 변경되면 내부에서 리렌더링시킨다.

### Recoil
- 최소 상태 단위인 atom이 RecoilRoot에서 만든 Context의 스토어에 등록되어 값이 관리된다. (이때 별도의 고유한 key 값으로 식별)
- 정식 버전이 릴리즈되지 않았으나, 최신 리액트에 잘 대응하고 있고, 앞으로도 계속 잘 지원할 것으로 기대된다.
### Jotai
- Recoil에서 영감을 얻어 만들어졌고 정식 출시되었기 때문에 Recoil의 대안으로 많이 사용된다.
- Recoil의 Context 리렌더링 문제를 해결하고자 설계됐다.
- Recoil과 달리 atom 객체 자체가 key로 저장되기 때문에 API가 간결하다.
### Zustand
- Redux에서 영감을 받아 만들어졌다.
- 하나의 스토어에서 중앙 집중적으로 상태 값들을 관리한다.
- 바닐라 환경에서도 사용 가능하다.
- 매우 가볍고 API가 간결하게 작성되어 쉽게 접근 가능하다.
- `persist`등의 미들웨어를 지원하여 세션스토리지에 저장하는 등의 추가적인 작업이 가능하다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

셋 모두 상태 관리 라이브러리, 리액트에서 많이 사용

Recoil
- Bottom Up 형태로 상태 관리
- 유니크한 key 값으로 구분되는 최소 상태 단위 atom을 Recoilroot에 등록하여 사용
- 정식 출시된 라이브러리가 아님

Jotai
- 리코일에서 영감을 받아 atom 개념 사용
- 리코일과 달리 key 값이 필요하지 않아 보일러 플레이트 코드가 짧음
- 리코일의 리렌더링 문제 해결

Zustand
- 바닐라 자바스크립트 상태 관리 라이브러리 (리액트 의존성 x)
- 리덕스에서 영감을 받아 탑다운 방식으로 하나의 큰 스토어를 만들어 상태 주입하는 방식
- 다른 라이브러리에 비해 굉장히 가벼운 번들 사이즈
- 리액트 18의 useSyncExternalStore를 통해 동작
- 다양한 미들웨어 사용 가능

</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
세개 모두 상태 관리 라이브러리로 Redux와 달리 별도의 리액트 패키지를 설치하지 않아도 상태가 변경되면 내부에서 리렌더링 시킵니다. 

1. Recoil
- atom 이라는 최소 상태 단위를 사용하며 atom을 통해 상태를 저장합니다. 
- atom은 key 값을 필수로 가지며, 이 키는 다른 atom과 구별하는 식별자로 필수 값입니다. 
- 리덕스와 다르게 추가적인 미들웨어(redux-saga, redux-thunk)를 사용하지 않더라도 selector을 필두로 다양한 비동기 작업을 지원하는 API를 제공합니다. 

2. Jotai
- Recoil과 다르게, atom 하나만으로 상태를 만들 수 있고 selector 없이도 파생된 상태를 만들 수도 있습니다. 
- 키 값을 필요로 하지 않습니다. 
- 상향식 접근법으로 작은 단위의 상태를 위로 전파할 수 있는 구조를 취하고 있습니다. 

3. Zustand
- 하나의 store를 중앙 집중형으로 활용해, store에서 상태를 관리합니다. 
- 많은 코드를 작성하지 않아도 빠르게 스토어를 만들고 사용할 수 있는 장점이 있습니다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
Recoil => atom이라는 작은단위의 상태를 관리, 
Jotai => recoil로부터 영향을 받음
Zustand => redux로 부터 영향을 받음

Recoil과 Jotai는 context API를 통해 상태를 관리하는 반면, Zustand는 하나의 중앙집중소?같은걸 만들어서 사용??
공통점으로는 셋다 상태관리 라이브러리이다..
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
- Recoil과 Jotai는 atom이라는 가장 작은 단위의 상태로 시작해서, atom을 합성하여 더 큰 파생 상태를 만들어나가는 방식으로 사용되며, Provider 기반으로 동작합니다.
- Zustand는 Redux의 아이디어를 차용한 상태 관리 라이브러리로, 하나의 큰 스토어에서 시작하여, selector로 점차 작은 파생 상태를 만들어나가는 방식으로 동작합니다.
</div>
</details>
