### ISSUE TITLE
[5장][동호] 리액트와 상태 관리 라이브러리

### ISSUE THREAD

**Issue by khakhiD** [KJ-StudyWithMe/modern-react-deep-dive#39]
### 퀴즈

아래 코드는 useState와 useReducer의 지역 상태를 벗어나기 위해 상태를 컴포넌트 레벨 바깥으로 분리하고자 시도하는 코드입니다. **리액트 관점에서 코드의 문제점**은 무엇인지 설명해주세요.

```tsx
export type State = { counter: number }

let state: State = {
  counter: 0,
}

export function get(): State {
  return state
}

type Initializer<T> = T extends any ? T | ((prev: T) => T): never

export function set<T>(nextState: Initializer<T>) {
  state = typeof nextState === 'function' ? nextState(state) : nextState
}

function Counter () {
  const state = get()

  function handleClick() {
    set((prev: State) => ({ counter: prev.counter + 1 }))
  }

  return (
    <>
      <h3>{state.counter}</h3>
      <button onClick={handleClick}>+</button>
    </>
  )
}

```

### 답

<details>
<summary>정답</summary>
<div markdown="1">

### **사건의 발단**
- useState는 리액트가 만든 클로저 내부에서 관리되어 지역 상태로 생성됨
- 컴포넌트가 초기화될 때마다 컴포넌트 인스턴스 별로 다른 상태를 가지게 됨
- 리액트 상태는 지역적으로만 상태 값이 유효하다는 한계가 존재

### **다른 곳에서 상태를 초기화하여 참조하게 하면 어떨까?**
- 하지만 이 코드는 **컴포넌트가 리렌더링되지 않음**
- state 값은 잘 업데이트 되는 것으로 보이나 UI가 업데이트되기 위해서는 리렌더링이 필요함
- 리렌더링을 위해서는 부모 함수가 리렌더링되거나 해당 컴포넌트(함수)가 재실행 되어야 함
- 위 코드는 부모 컴포넌트가 없고, props도 없으므로 일일이 Counter()를 재실행 시켜야만 리렌더링됨
- 이는 매우 비효율적임

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
여러개의 컴포넌트에서는 못쓴다?
이를 위해 부모 컴포넌트에 store를 만들고 자식컴포넌트에게 props를 넘겨주거나 context를 사용하여 여러 컴포넌트에게 상태를 전달할수있다.
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

값이 변경되어도 컴포넌트가 리렌더링되지 않기 때문에 문제가 된다. 리액트는 useState, useReducer가 반환하는 상태 값에 변화가 있을 때 리렌더링을 시키지만 주어진 코드에서의 상태는 이 훅들로 관리되지 않기 때문에 리렌더링되지 않는다.
</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
state 값이 변경되어도 컴포넌트가 리렌더링되지 않아 변경된 값이 반영이 안되는 문제가 있습니다. 
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
React 외부의 모듈 레벨에서 상태가 관리되고 있기에, `handleClick` 이벤트 핸들러로 상태를 변경하더라도 리액트가 변화를 감지하여 리렌더링하는 동작을 수행하지 못합니다. 이를 해결하기 위해서는 `useState` 와 `useEffect` 로 외부 모듈 레벨에서의 상태를 리액트와 연동하는 어댑터 역할을 수행하는 로직을 작성하거나, 리액트 18버전에서 도입된 `useSyncExternalStore` 훅을 사용합니다.
</div>
</details>
