### ISSUE TITLE
[1장][다은] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by GBAJS754** [KJ-StudyWithMe/modern-react-deep-dive#4]
### 퀴즈

면접 질문 : 아래의 코드를 보고 Component와 DeeperComponent 두 컴포넌트의 렌더링 관점에서의 차이점과 memo가 어떻게 동작하는지에 대해 설명해주세요!

```jsx
type ComponentProps = {
  counter: number,
};

type DeeperComponentProps = {
  counter: {
    counter: number,
  },
};

const Component = memo((props: ComponentProps) => {
  useEffect(() => {
    console.log("Component render");
  });

  return <h1>{props.counter}</h1>;
});

const DeeperComponent = memo((props: DeeperComponentProps) => {
  useEffect(() => {
    console.log("DeeperComponent render");
  });

  return <h1>{props.counter.counter}</h1>;
});

function App() {
  const [, setCounter] = useState(0);

  return (
    <>
      <Component counter={100}></Component>
      <DeeperComponent counter={{ counter: 100 }}></DeeperComponent>
      <button
        onClick={() => {
          setCounter((prev) => prev + 1);
        }}
      >
        {" "}
      </button>
    </>
  );
}

export default App;
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
정답은 없습니다. 면접질문이다 라고 생각하고 자신의 의견을 써주시면 됩니다!
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
Component: 리액트가 얕은 비교까지 수행해 props의 변화가 없음을 인지하고 리렌더링되지 않는다 (memo 정상 동작)  

DeeperComponent: 역시 props의 변화가 없음에도 중첩된 객체가 있어 얕은비교까지 하는 리액트는 안에까지 비교를 못해서 리렌더링 시킨다. (memoization 안됨!)

즉 memo는 객체의 얕은 비교까지 수행했을 때 동일하다(props의 변화가 없다)고 판단하면 메모이제이션된 컴포넌트를 반환한다.
</div>
</details>

**Comment by jkea1** [comment]
`memo(component)` 의 경우 최적화된 컴포넌트를 반환해 주는데 렌더링 되는 상황에 놓일 때 마다`props`에 변화가 있는지 확인해서 변화가 있을 때 만 렌더링하고, 없다면 그 전에 메모이징 했던 내용을 재사용 합니다. 
하지만 리액트에서 props 비교는 `shallowEqual` 함수를 이용해서 얕은 비교만 수행합니다. 따라서 `ComponentProps`의 props의 경우에는 얕은 비교를 통해 정확히 객체간의 비교를 수행하여 렌더링을 방지해 주었지만,`DeeperComponentProps`의 경우에는 props가 중첩되어 있는 구조이기 때문에 얕은 비교로는 제대로 비교하지 못해 `memo()`의 메모이제이션이 작동하지 못하고 `DeeperComponent`가 재렌더링 됩니다.

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
React.memo 고차 함수는 래핑된 컴포넌트를 메모이제이션합니다.
기본적으로 리액트에서 부모 컴포넌트가 리렌더링되면 자식 컴포넌트도 함께 리렌더링이 되는데, React.memo로 감싼 자식 컴포넌트의 경우 이전에 메모이제이션 했던 스냅샷과 현재 리렌더링 하려는 스냅샷의 props를 비교하여, 동일하다면 리렌더링을 생략하여 불필요한 렌더링을 줄일 수 있습니다.


현재 코드에서 Component의 props에는 원시 타입의 counter를 전달받고, DeeperComponent의 props에는 참조 타입의 counter를 전달받고 있습니다.
JS에서 참조 타입의 경우에는 내부의 프로퍼티에 존재하는 값이 동일하다고 하더라도 선언된 시점에 따라서 두 객체는 다른 값을 가진 것으로 인식합니다. (참조하고 있는 메모리 주소가 다르기 때문)
따라서 Component는 의도한 대로 메모이제이션이 동작해 리렌더링을 생략하고, DeeperComponent는 항상 리렌더링을 유발합니다.


그런데 리액트에서 컴포넌트가 부모로부터 전달받는 props도 사실 객체 타입이기에, 이전 스냅샷의 props와 현재 스냅샷의 props를 비교하는 것이 사실 불가능합니다.
따라서 리액트는 props의 비교를 위해서 내부 프로퍼티를 1단계 깊이로 비교하여 체크하는 shallowEquals 함수를 구현해서 내부적으로 사용하고 있습니다.

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

리액트는 일반적으로 부모 컴포넌트가 리렌더링될 때마다 자식 컴포넌트를 리렌더링한다.  `Component`와 `DeeperComponent` 두 컴포넌트 모두 `memo` 함수로 감싸져 있는데, `memo` 함수는 컴포넌트의 프로퍼티가 변경되었을 때만 해당 컴포넌트를 리렌더링하도록 제어하여 불필요한 리렌더링을 방지하는 역할을 한다.

원시 타입인 숫자를 프로퍼티로 받는 `Component`는 `memo` 함수의 기능이 수행되지만, 참조 타입인 객체를 프로퍼티로 받는 `DeeperComponent`는 `memo`의 기능이 의도대로 동작하지 않는다. 이는 리액트가 동등 비교에 얕은 비교를 활용하기 때문이다. 얕은 비교란 동등 비교에서 객체와 객체의 값이 같은 지 확인하는 경우 객체 내부 구조가 아닌 참조 값만 비교한다는 것을 의미한다.

 `DeeperComponent`의 경우 객체를 프로퍼티로 받으므로 객체의 내부 값(`counter`)이 변경되더라도 객체의 참조 값이 변경되지 않으면 이전 프로퍼티의 참조 값과 변경된 프로퍼티의 참조 값이 동일하므로 리렌더링이 일어나지 않아야 한다. 하지만 리액트에서는 얕은 비교를 객체의 1depth까지는 비교할 수 있게 구현하여 객체의 1depth 내 속성 값이 변하는 것을 감지할 수 있다.

만약 프로퍼티가 객체 내부에 또 다른 객체가 있어서 1depth 이상이 깊이를 가진다면 그 깊이부터 리액트는 객체 구조의 변경을 감지하지 못한다. 더 깊은 구조의 객체를 프로퍼티로 가질 경우에는 깊은 비교를 사용하여 구현해야 한다.


</div>
</details>
