### ISSUE TITLE
[10장][다은] 리액트 17과 18의 변경 사항 살펴보기

### ISSUE THREAD

**Issue by GBAJS754** [KJ-StudyWithMe/modern-react-deep-dive#44]
### 퀴즈

1. debounce 대비 useDeferredValue의 장점에 대해 설명해주세요!
2. useTransition과 useDeferredValue의 차이점에 대해 설명해주세요!

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
 1. 디바운스는 고정된 지연 시간이 필요한 반면, useDeferredValue는 고정된 지연시간없이 첫번째 렌더링이 완료된 이후에 이 useDeferredValue로 지연된 렌더링을 수행한다. 그러므로 이 지연된 렌더링은 중단할수있으며 사용자의 인터랙션을 차단하지도 않는다.
 2. useTransition은 state값을 업데이트 하는 함수를 감싸서 사용하는 반면, useDeferredValue는 state값 자체만을 감싸서 사용한다. 즉, 함수를 감싸냐 값을 감싸냐의 차이, 지연된 렌더링을 한다는 점에서는 동일하다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. 일반적으로 사용되는 디바운스 함수와 비슷하지만 장점이 더 있음
    - 디바운스는 고정된 지연 시간이 필요하지만, 고정된 지연 시간이 필요하지 않음
    - 또한 지연된 렌더링을 중단할 수 있으며, 사용자 인터랙션을 차단하지 않음

<br />

2. 둘 다 컴포넌트의 렌더링을 지연시킬 수 있는 훅
    - `useTransition`는 state 값을 업데이트하는 함수를 감싸서 사용, 낮은 우선순위로 처리해야 할 작업에 직접적으로 상태를 업데이트할 수 잇는 코드에 접근할 수 있다면 사용
    - `useDeferredValue`는 state 값 자체만을 감싸서 사용, 컴포넌트의 props와 같이 상태 업데이트에 관여할 수는 없고 오로지 값만 받아야 하는 상황에 사용


</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. useDeferredValue를 사용하면 고정된 지연 시간을 전달하지 않아도 된다.
2. useTransition은 상태 업데이트 함수를 전달해야하지만, useDeferredValue는 상태 값 자체를 전달하기 때문에 props로 상태를 받아 쓰는 경우처럼 직접 상태 업데이트를 하지 못할 때 사용하기 좋다.
</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 디바운스는 고정된 지연 시간이 필요한 반면, useDeferredValue는 고정된 지연 시간 없이 첫번째 렌더링이 완료된 이후에 이 useDeferredValue로 지연된 렌더링을 수행합니다. 

2. useTransition은 state값 을 업데이트 하는 함수를 감싸서 사용하는 반면, useDeferredValue는 state 값 자체만을 감싸서 사용한다. 렌더링을 지연시킨다는 점이 동일합니다. 
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. debounce 대비 useDeferredValue의 장점에 대해 설명해주세요!
- debounce는 특정 단위 시간을 입력하는 것이 필요하기 때문에, 비동기 작업을 보다 빨리 수행하는 것도 가능한 경우더라도 무조건 단위 시간만큼은 기다려야 합니다. 그러나 `useDeferredValue` 는 React의 동시성 렌더링을 활용하여, 더 신속하게 업데이트해야 하는 `Lane` 에 아무런 작업도 존재하지 않는다면, 곧바로 `Concurrent Lane` 의 작업을 수행할 수 있습니다.

2. useTransition과 useDeferredValue의 차이점에 대해 설명해주세요!
- `useTransition` 은 상태 업데이트 동작 자체를 유예하고, `useDeferredValue` 는 값 업데이트를 유예합니다.


</div>
</details>
