### ISSUE TITLE
[10장][민희] 리액트 17과 18의 변경사항 살펴보기

### ISSUE THREAD

**Issue by leeminhee119** [KJ-StudyWithMe/modern-react-deep-dive#48]
### 퀴즈

```tsx
import { useEffect, useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);
  const [isClicked, setIsClicked] = useState(false);

  useEffect(() => {
    console.log('rendered!');
  });

  function handleClick() {
    setTimeout(() => {
      setCount((c) => c + 1);
      setIsClicked((i) => !i);
    }, 2000);
  }

  return (
    <>
      <h1>isClicked: {isClicked ? 'yes' : 'no'}</h1>
      <h1>count: {count}</h1>
      <button onClick={handleClick}>+</button>
    </>
  );
}
```
위 컴포넌트에서 button을 클릭했을 때 콘솔에 rendered가 몇 번 출력되나요? (버전은 18입니다.)

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

리액트 18부터는 위의 예시처럼 setTimeout을 포함한 비동기 이벤트에서도 자동 배치가 이루어지기 때문에 setState함수가 두 번 실행되었어도 변경사항들을 묶어 한 번의 리렌더링만 실행하기 때문에 **한 번** 출력됩니다. (최초 렌더링 제외)
단, 리액트 17이하의 버전에서는 비동기 이벤트에 대해서는 자동 배치가 이루어지지 않기 때문에 setState 함수를 호출한 횟수만큼 리렌더링 되어 두 번 출력됩니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

첫 번째 렌더링이 될 때, `rendered!`가 콘솔에 찍힌다.

버튼이 클릭되었을 때, 2000ms 뒤 `rendered!`가 콘솔에 찍힌다.

(리액트 18의 업데이트로 인해 비동기 이벤트에 대해서도 자동 배칭이 동작함)

</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
답은 한번, 
setState가 두번 호출됐지만 배칭으로 인해 한번에 처리되기때문이다.
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
- 총 2회 출력! (비 엄격모드 기준)
- 1. 초기 렌더링에서 실행
- 2. 버튼 클릭 후 `setTimeout` 의 콜백이 2초 후에 실행되는데, 이 부분에 배칭 업데이트가 적용되기에 리렌더링이 1번 발생.
</div>
</details>

**Comment by jkea1** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
자동 배칭 작업으로 인해 버튼을 누르고 2초 뒤에 리렌더링이 일어나 'rendered!' 가 한 번 출력됩니다. 
</div>
</details>
