### ISSUE TITLE
[10장][진경] 리액트 17과 18의 변경사항 살펴보기

### ISSUE THREAD

**Issue by jkea1** [KJ-StudyWithMe/modern-react-deep-dive#49]
### 퀴즈

리액트 18의 새로운 훅 `useDeferredValue` 와 `useTransition`은 어떤 공통점과 차이점이 있나요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- 공통점
  - 렌더링을 지연시키는 역할을 합니다. 

- 차이점
  - `useTransition`은 state 값을 업데이트하는 함수를 감싸서 사용하는 반면, `useDeferredValue`은 state 값 자체만을 감싸서 사용합니다. 
  - props와 같이 상태 업데이트에 관여 할 수 없고 오직 값만 받아야 하는 상황이라면 `useDeferredValue`를 사용하는 것이 타당하고, 직접적으로 상태를 업데이트 할 수 있는 코드에 접근 할 수 있다면 `useTransition`을 사용 하는 것이 좋습니다. 

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">


둘 다 컴포넌트의 렌더링을 지연시킬 수 있는 훅이다.

`useTransition`는 state 값을 업데이트하는 함수를 감싸서 사용하고, 낮은 우선순위로 처리해야 할 작업에 직접적으로 상태를 업데이트할 수 있는 코드에 접근할 수 있다면 사용한다.

`useDeferredValue`는 state 값 자체만을 감싸서 사용하고, 컴포넌트의 props와 같이 상태 업데이트에 관여할 수는 없고 오로지 값만 받아야 하는 상황에 사용한다.

</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
둘다 동시성을 지원하는 공통점이있지만 useDeferredValue는 값을 useTransition는 함수를 지연할때 쓰인다.
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

useDeferredValue는 useTransition과 마찬가지로 상태가 변경되었을 때 관련된 렌더링을 뒤로 지연시킬 수 있다는 역할을 하는 점에서 동일하지만, 상태 업데이트 함수를 직접 전달해야 하는 useTransition과 다르게 상태값 자체를 전달한다는 차이가 있다. 따라서 props로 값을 받아와서 렌더링하는 컴포넌트의 경우 useDeferredValue로 전달받은 상태값을 감싸면 해당 상태 값이 바뀌었을 때 렌더링을 지연시킬 수 있다.
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
공통점: 렌더링 과정에서 연산이 오래 걸리는 작업의 경우, UI를 Blocking하는 현상이 발생할 수 있는데 이 부분을 방지하기 위해 상태 업데이트의 우선순위를 미루는 동시성 렌더링 기능을 위한 훅입니다.

useTransition은 상태 업데이트 동작 자체를 유예하고, useDeferredValue는 값 업데이트를 유예합니다.

</div>
</details>
