### ISSUE TITLE
[1장][진경] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by jkea1** [KJ-StudyWithMe/modern-react-deep-dive#9]
### 퀴즈

자바스크립트에서 이벤트 루프는 어떤 역할을 하나요? 

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
자바스크립트의 비동기 실행을 돕기 위해 만들어진 장치 입니다. (이벤트 루프는 태스크 큐를 한 개 이상 가지고 있습니다.)
호출 스택에 실행 중인 코드가 있는지, 그리고 태스크 큐에 대기 중인 함수가 있는지 반복해서 확인하는 역할을 합니다. 호출 스택이 비었다면 태스크 큐에 대기 중인 작업이 있는지 확인하고, 이 작업을 실행 가능한 오래된 것부터 순차적으로 꺼내와서 실행하게 됩니다. 이 작업 또한 마찬가지로 태스크 큐가 빌 때까지 이루어 집니다. 
</div>
</details>

**Comment by leeminhee119** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
싱글 스레드로 작동하는 자바스크립트가 여러 작업을 비동기로 처리할 수 있도록 돕는다.  

콜 스택이 비어있는지 확인하고, 비어있는 경우 태스크 큐로 옮겨졌던 작업들을 다시 콜스택으로 옮겨 자바스크립트가 실행하도록 처리한다.
</div>
</details>

**Comment by GBAJS754** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
이벤트 루프는 콜스택이 비어있는지 수시로 확인하며, 콜스택이 비어있으면 태스크큐에 있는 비동기 작업을 콜스택으로 옮겨주는 역할을 합니다
</div>
</details>

**Comment by bbearcookie** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
이벤트 루프는 JS의 콜 스택이 비어있는 것을 Polling으로 체크하고, 콜백 큐에서 완료된 비동기 작업에 대한 콜백 함수를 우선순위가 높은 순서로 콜 스택으로 옮겨주는 역할을 수행합니다.
즉, 싱글 스레드로 동작하는 자바스크립트에서도 논 블록킹 방식의 비동기 처리를 수행할 수 있도록 도와주는 매커니즘입니다.
브라우저에서는 Web API에게 비동기 작업의 처리를 위임하고, Node.js 에서는 libuv에게 위임합니다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

이벤트 루프는 싱글 스레드로 동작하는 자바스크립트 엔진이 비동기 작업을 처리할 수 있도록 하는 장치다. 자바스크립트 엔진 내의 호출 스택, 콜백 큐, Web API 등 여러 요소들을 확인하며 비동기적으로 실행되어야 하는 작업을 관리하고 순서대로 처리하여 프로그램의 실행 흐름을 제어하는 역할을 한다.


</div>
</details>
